name: skarb_plugin
description: A new Flutter plugin project.
version: 3.0.5

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  intl: ^0.19.0
  flutter_keychain: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bitlica.skarb_plugin
        pluginClass: SkarbPlugin
      ios:
        pluginClass: SkarbPlugin
