name: skarb_plugin
description: Skarb flutter project.
version: 3.3.6

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bitlica.skarb_plugin
        pluginClass: SkarbPlugin
      ios:
        pluginClass: SkarbPlugin
